import { ThemePalette, ThemePresetId, MemoryCategoryType } from '../types';

export const THEME_PALETTES: Record<ThemePresetId, ThemePalette> = {
  midnight_amber: {
    id: 'midnight_amber',
    englishName: 'Midnight Amber',
    tamilName: 'Pon Andhi',
    description: 'Serene obsidian with luminous warm amber gold glow',
    background: '#0B0F17',
    surface: '#141C28',
    card: '#182232',
    border: '#222E42',
    primary: '#E09858',
    primaryLight: '#F0B27A',
    primaryDark: '#B86B28',
    accentGlow: 'rgba(224, 152, 88, 0.4)',
    secondary: '#5A9E8F',
    textPrimary: '#F3F5F9',
    textSecondary: '#A6B2C4',
    textMuted: '#6E7D93',
  },
  temple_gold: {
    id: 'temple_gold',
    englishName: 'Sacred Temple Gold',
    tamilName: 'Kovil Thangam',
    description: 'Sacred imperial navy with traditional gold and brass elegance',
    background: '#0C1019',
    surface: '#151E2E',
    card: '#1A263B',
    border: '#2A3A54',
    primary: '#E5B842',
    primaryLight: '#F5CE68',
    primaryDark: '#C29524',
    accentGlow: 'rgba(229, 184, 66, 0.4)',
    secondary: '#E07A5F',
    textPrimary: '#F8F6F0',
    textSecondary: '#BAC3D6',
    textMuted: '#7585A2',
  },
  sandalwood_rose: {
    id: 'sandalwood_rose',
    englishName: 'Sandalwood & Rose',
    tamilName: 'Sandhanam & Roja',
    description: 'Deep warm mahogany with heartfelt rose gold warmth',
    background: '#130E14',
    surface: '#1E1620',
    card: '#261C29',
    border: '#3A2B3E',
    primary: '#E88B9E',
    primaryLight: '#F5A8B7',
    primaryDark: '#C76277',
    accentGlow: 'rgba(232, 139, 158, 0.4)',
    secondary: '#D4A373',
    textPrimary: '#FBF4F6',
    textSecondary: '#C7B3C0',
    textMuted: '#867280',
  },
  forest_sage: {
    id: 'forest_sage',
    englishName: 'Serene Forest Sage',
    tamilName: 'Thulasi & Vanam',
    description: 'Peaceful spruce evergreen with healing jade and herbal sage',
    background: '#0A1310',
    surface: '#12201B',
    card: '#182B24',
    border: '#244036',
    primary: '#5EB69D',
    primaryLight: '#7ECEB7',
    primaryDark: '#3E8D77',
    accentGlow: 'rgba(94, 182, 157, 0.4)',
    secondary: '#81B29A',
    textPrimary: '#F0F7F4',
    textSecondary: '#ACBEB7',
    textMuted: '#6B8077',
  },
  royal_amethyst: {
    id: 'royal_amethyst',
    englishName: 'Royal Amethyst',
    tamilName: 'Raja Oodha',
    description: 'Celestial twilight with timeless spiritual lavender glow',
    background: '#100D18',
    surface: '#1C162B',
    card: '#241C36',
    border: '#362A52',
    primary: '#AF88F0',
    primaryLight: '#C8A7FC',
    primaryDark: '#8E5EE0',
    accentGlow: 'rgba(175, 136, 240, 0.4)',
    secondary: '#70C1B3',
    textPrimary: '#F5F2FB',
    textSecondary: '#BEB5D2',
    textMuted: '#7D7296',
  },
  amoled_onyx: {
    id: 'amoled_onyx',
    englishName: 'True AMOLED Onyx',
    tamilName: 'Muzhu Karuppu',
    description: '100% pure OLED black with vivid solar amber highlights',
    background: '#000000',
    surface: '#0F0F0F',
    card: '#161616',
    border: '#262626',
    primary: '#F59E0B',
    primaryLight: '#FBBF24',
    primaryDark: '#D97706',
    accentGlow: 'rgba(245, 158, 11, 0.4)',
    secondary: '#10B981',
    textPrimary: '#FFFFFF',
    textSecondary: '#A3A3A3',
    textMuted: '#525252',
  },
  light_linen: {
    id: 'light_linen',
    englishName: 'Ivory Linen',
    tamilName: 'Vellai & Sandhanam',
    description: 'Warm daylight linen with antique bronze and parchment notes',
    background: '#FAF7F2',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    border: '#E8DFD3',
    primary: '#B86B28',
    primaryLight: '#D99153',
    primaryDark: '#8F4D14',
    accentGlow: 'rgba(184, 107, 40, 0.25)',
    secondary: '#4D8578',
    textPrimary: '#231F1C',
    textSecondary: '#5E574E',
    textMuted: '#8F867B',
  },
};

export const CATEGORY_CONFIG: Record<
  MemoryCategoryType,
  { label: string; color: string; bgLight: string }
> = {
  personal: {
    label: 'Personal',
    color: '#D47A60',
    bgLight: 'rgba(212, 122, 96, 0.15)',
  },
  family: {
    label: 'Family',
    color: '#5B9E78',
    bgLight: 'rgba(91, 158, 120, 0.15)',
  },
  stories: {
    label: 'Stories',
    color: '#638ECB',
    bgLight: 'rgba(99, 142, 203, 0.15)',
  },
  events: {
    label: 'Important Events',
    color: '#B8860B',
    bgLight: 'rgba(184, 134, 11, 0.15)',
  },
  favorites: {
    label: 'Favourite Things',
    color: '#9B6BB0',
    bgLight: 'rgba(155, 107, 176, 0.15)',
  },
  messages: {
    label: 'Messages',
    color: '#4B9DA3',
    bgLight: 'rgba(75, 157, 163, 0.15)',
  },
};

export const VOICE_STATE_COLORS = {
  ready: '#9E86C8', // Soft serene lavender
  listening: '#48CAE4', // Responsive sky cyan
  processing: '#F4A261', // Thoughtful warm amber
  speaking: '#E76F51', // Expressive gentle coral
};
